### ISSUE TITLE
Add Login Screen

### ISSUE THREAD

**Issue by pratyushmp** [pratyushmp/Batua#1]

**Comment by ShrutiJ-01** [comment]
I would like to work on it!

**Comment by pratyushmp** [comment]
@ShrutiJ-01 Sure! The issue will be assigned once the coding period starts.

**Comment by SapinderSingh** [comment]
I want to work on this issue.

**Comment by rudranshawasthi** [comment]
I would like to work on it

**Comment by pratyushmp** [comment]
Sorry @rudranshawasthi. Issue is already assigned. Meanwhile you can look at other unassigned issues to contribute!

**Comment by rudranshawasthi** [comment]
Sorry I didn't see your message. I have created a pull request you can merge it if you like.

**Comment by pratyushmp** [comment]
@rudranshawasthi Sorry since I had assigned the issue to someone else, I cannot merge your PR. But I appreciate your participation. More issues will be created soon, will be looking forward for your contribution!

**Comment by STARLORD3** [comment]
@pratyushmp can I work on this?

**Comment by pratyushmp** [comment]
@ShrutiJ-01 Status of login Screen?

**Comment by ShrutiJ-01** [comment]
Almost done, will be making a PR soon👍

**Comment by pratyushmp** [comment]
Cool!
