### ISSUE TITLE
Firebase Authentication using Email and Password 

### ISSUE THREAD

**Issue by Abhishek-dab** [pratyushmp/Batua#10]
Hey!! I would like to work on adding login and sign-in functionality by using firebase authentication using email and password under gssoc'21. This issue is not yet present here. Thank You.

**Comment by pratyushmp** [comment]
Sure @Abhishek-dab. But you will have to wait until the Login and Sign Up pages are developed! After that you can start working on it.

**Comment by pratyushmp** [comment]
Also share your email address so that I can add you in the Firebase Project

**Comment by Abhishek-dab** [comment]
@pratyushmp Sure I will DM you my Email ID in the discord itself.

**Comment by pratyushmp** [comment]
No problem! :)

**Comment by pratyushmp** [comment]
@Abhishek-dab Status of Firebase Authentication?

**Comment by Abhishek-dab** [comment]
@pratyushmp  Done with everything just need to make a PR. I will do that before 6 pm.

**Comment by pratyushmp** [comment]
Cool!
