### ISSUE TITLE
Unable to run set up project

### ISSUE THREAD

**Issue by iamsamuelhere** [pratyushmp/Batua#13]
![image](https://user-images.githubusercontent.com/60421298/110804545-4a707c80-82a6-11eb-9ecf-d8462614ef2a.png)

Reason :
- Project does not contain **google-services.json** file which is available during registering app in Firebase

Is the project registered on Firebase?

**Comment by pratyushmp** [comment]
The project is registered on Firebase, but I have chosen not to upload the google-services.json file since Git Guardian keeps sending mails saying that your API key is exposed. 
Link to the google-services.json file is provided in the README.md
