### ISSUE TITLE
The app is not running on iOS devices 

### ISSUE THREAD

**Issue by rohats871** [pratyushmp/Batua#16]
The app is not working on iOS devices which are running on iOS 9 and below plus if you have to test run them you need to make some changes

**Comment by infiniteoverflow** [comment]
Hi @rohats871 , thanks for raising this issue. The iOS version has been set to 10 due to the dependency of cloud_firestore in the app. This issue is now fixed.

Meanwhile feel free to raise an issue with the working of the app or any feature you would like to add.

**Comment by rohats871** [comment]
the app is still not working
