### ISSUE TITLE
Make HomePage responsive for small devices like iPhone

### ISSUE THREAD

**Issue by rohats871** [pratyushmp/Batua#18]
<img width="384" alt="110946490-eeb8f880-8364-11eb-9ec6-9ac73c397505" src="https://user-images.githubusercontent.com/68010359/111026605-0f3e8c80-8411-11eb-82b9-b817ee29510b.png">

**Comment by anotherwebguy** [comment]
Hey can i work on this issue plz assign me this @rohats871

**Comment by pratyushmp** [comment]
Sure @anotherwebguy  !

**Comment by anotherwebguy** [comment]
> Sure @anotherwebguy !

Thanks for assigning me this issue @pratyushmp
