### ISSUE TITLE
Add Sign Up Screen

### ISSUE THREAD

**Issue by pratyushmp** [pratyushmp/Batua#2]

**Comment by Samdid** [comment]
@pratyushmp please assign it to me under GSSOC21'

**Comment by Manzee1609** [comment]
I would like to work on this issue
(I have previous experience)

**Comment by pratyushmp** [comment]
@Samdid Issue has been assigned to you!

**Comment by STARLORD3** [comment]
@pratyushmp can I work on this?

**Comment by pratyushmp** [comment]
@Samdid Status of progress in Sign Up Screen?
