### ISSUE TITLE
User Details Screen

### ISSUE THREAD

**Issue by pratyushmp** [pratyushmp/Batua#22]
Develop the screen as per the UI design given below.

Follow the color schemes defined in the file ```constants.dart.```

On clicking the ```submit``` button just print the input values in the console. Once the design of Firebase Database is decided upon we will update the values there.

![Screenshot (209)](https://user-images.githubusercontent.com/42929557/111112713-a5e08a00-8586-11eb-9227-b3a8d71b56fb.png)

**Comment by D-Ajay-Kumar** [comment]
Can do it

**Comment by EAsmithaShrree** [comment]
Hey, can you please assign this issue to me? I am a part of GSSOC'21.

**Comment by pawan2806** [comment]
Can I work on this under GSSOC21?

**Comment by nirala96** [comment]
Sure @D-Ajay-Kumar go for it. @EAsmithaShrree and @pawan2806 new issues for you will be opened soon.

**Comment by D-Ajay-Kumar** [comment]
Thanks. On it.

**Comment by D-Ajay-Kumar** [comment]
<img src="https://user-images.githubusercontent.com/56850266/111148776-0df89580-85b2-11eb-8eaf-408aaf7b0f97.jpeg" data-canonical-src="https://user-images.githubusercontent.com/56850266/111148776-0df89580-85b2-11eb-8eaf-408aaf7b0f97.jpeg" width="360" height="650" />

<img src="https://user-images.githubusercontent.com/56850266/111148789-1224b300-85b2-11eb-81ca-41b0fd21e768.jpeg" data-canonical-src="https://user-images.githubusercontent.com/56850266/111148789-1224b300-85b2-11eb-81ca-41b0fd21e768.jpeg" width="360" height="650" />

How do these look?

**Comment by pratyushmp** [comment]
Use Extended Widget to bring everything in one screen.

**Comment by D-Ajay-Kumar** [comment]
![WhatsApp Image 2021-03-15 at 6 53 20 PM](https://user-images.githubusercontent.com/56850266/111160134-d1cc3180-85bf-11eb-8d3b-c1bd3ef8c4e1.jpeg)

How's this?

**Comment by infiniteoverflow** [comment]
Looks great . @pratyushmp  ?

**Comment by D-Ajay-Kumar** [comment]
Shall I make the hint text a lil lighter? It looks dark considering it's just for hinting what to type.

**Comment by pratyushmp** [comment]
@D-Ajay-Kumar  Yup! That's a good idea, make the hint text a tad bit lighter and great job with the Loading Screen!

**Comment by D-Ajay-Kumar** [comment]
Done. Please check the code :)
