### ISSUE TITLE
Replacing deprecated elements

### ISSUE THREAD

**Issue by amanxnanda** [pratyushmp/Batua#25]
![image](https://user-images.githubusercontent.com/34944818/111170768-50c66780-85ca-11eb-8cf5-9a96233f7a4a.png)

It's nice to replace deprecated elements like Flatbutton and Raisedbutton. If this gets assigned to me I like to replace them with TextButton and ElevatedButton respectively.

**Comment by pratyushmp** [comment]
Sure @amanxnanda . You can go ahead!

**Comment by amanxnanda** [comment]
Thanks.
