### ISSUE TITLE
Add Google Sign In

### ISSUE THREAD

**Issue by pratyushmp** [pratyushmp/Batua#3]

**Comment by ShrutiJ-01** [comment]
I would like to work on this issue

**Comment by Manzee1609** [comment]
I would like to work on this issue
(I have used firebase signin my personal flutter projects)

**Comment by pratyushmp** [comment]
Great to see the participation, but the issues will be assigned after the coding period starts!

**Comment by pratyushmp** [comment]
@Manzee1609 issue assigned to you!

**Comment by Manzee1609** [comment]
Waiting for login screen to get implemented

**Comment by pratyushmp** [comment]
Yup No problems!

**Comment by Manzee1609** [comment]
Pls add me to the firebase project :)
email - mansikalaria16@gmail.com

**Comment by pratyushmp** [comment]
Added!

**Comment by pratyushmp** [comment]
@Manzee1609 The Login page is created, you can work on the Google Sign In now.

**Comment by Manzee1609** [comment]
Okay!! I will create pr by tommorow eve
