### ISSUE TITLE
Sign Up , Log in button not working 

### ISSUE THREAD

**Issue by Borahb** [pratyushmp/Batua#34]
The Sign up Button is not working. Also, the code for login button is missing. 
Can I Solve it?

#gssoc21

**Comment by pratyushmp** [comment]
@Borahb Could you include a video of the sign up button not working?

**Comment by Borahb** [comment]
okay

**Comment by Borahb** [comment]
https://user-images.githubusercontent.com/49881148/111736158-4a264180-88a3-11eb-92f3-8378c61c99a4.mp

This is the clip.

**Comment by pratyushmp** [comment]
Okay @Borahb , Go ahead the issue is assigned to you!

**Comment by pratyushmp** [comment]
Make sure that after successful login/sign up, you navigate the user to the home screen.

**Comment by Borahb** [comment]
okay
