### ISSUE TITLE
Add Email Verification for new users using Firebase

### ISSUE THREAD

**Issue by pratyushmp** [pratyushmp/Batua#38]

**Comment by SamarpanCoder2002** [comment]
> _No description provided._

hello @pratyushmp ..... Can I proceed with that? I also use that in other projects.... I can do it perfetctly.... If I can forward with that, please assign to me here... Thanks @pratyushmp

**Comment by pratyushmp** [comment]
Sure @SamarpanCoder2002 . You can go ahead!

**Comment by SamarpanCoder2002** [comment]
> Sure @SamarpanCoder2002 . You can go ahead!

Thanks for assign me..I will make a pull request soon

**Comment by SamarpanCoder2002** [comment]
> Sure @SamarpanCoder2002 . You can go ahead!

@pratyushmp  To forward with that, I need to access firebase account related to this project..... Please assign the firebase account with my mail id(make me collaborator in that firebase account)........my gmail: samarpanofficial2021@gmail.com

**Comment by SamarpanCoder2002** [comment]
> > Sure @SamarpanCoder2002 . You can go ahead!
> 
> @pratyushmp To forward with that, I need to access firebase account related to this project..... Please assign the firebase account with my mail id(make me collaborator in that firebase account)........my gmail: [samarpanofficial2021@gmail.com](mailto:samarpanofficial2021@gmail.com)

Thank you @pratyushmp

**Comment by pratyushmp** [comment]
@SamarpanCoder2002 I have added you as a collaborator in the Firebase Project.

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 I have added you as a collaborator in the Firebase Project.

Thanks a lot for that.....

**Comment by pratyushmp** [comment]
No probs! :)
