### ISSUE TITLE
Make the Password and Confirm Password field in the Sign Up screen obscured.

### ISSUE THREAD

**Issue by pratyushmp** [pratyushmp/Batua#43]

**Comment by D-Ajay-Kumar** [comment]
Can do it

**Comment by pratyushmp** [comment]
@D-Ajay-Kumar Sure! Go ahead

**Comment by D-Ajay-Kumar** [comment]
This pubspec.lock file got changed on it's own, does this file change automatically according to the Flutter settings on one's computer?
