### ISSUE TITLE
Adding back button on sign up screen which will take us back to login screen

### ISSUE THREAD

**Issue by Samdid** [pratyushmp/Batua#44]
### Feature request :
A back button which will take us to the previous screen.

### Describe the solution you'd like :
An user is logging in the app and by mistake click on the "create one" option and navigate to sign up screen, so he needs to get back to the login screen and for that there should be a back button sign up screen.
![Screenshot_1616396293](https://user-images.githubusercontent.com/70087884/111951842-329cc200-8b0a-11eb-8604-1ebf8e4146a0.png)

### Describe alternatives you've considered :
As an alternative, we can add a clickable text "login" instead of a back button.

### Describe how this feature will be useful to our readers :
It is useful to reader everytime he goes to signup screen and wants get back to login screen.

Also, I am a GSSoC21' participant and want to add this feature

<hr/>

**Comment by pratyushmp** [comment]
Good idea @Samdid . Add a simple "arrow" icon which takes the user back.

**Comment by Samdid** [comment]
@pratyushmp Sure
