### ISSUE TITLE
Add the User's registered email from login to Firebase database

### ISSUE THREAD

**Issue by pratyushmp** [pratyushmp/Batua#48]

**Comment by pawan2806** [comment]
Can I work on this under gssco21 @pratyushmp?

**Comment by pratyushmp** [comment]
Sure @pawan2806 . The issue is assigned to you!

**Comment by pawan2806** [comment]
Can you give me access to the database pawansingh102938@gmail.com .

**Comment by pratyushmp** [comment]
Done @pawan2806

**Comment by pawan2806** [comment]
> Done @pawan2806

Permissions to manage cloud firestore is required @pratyushmp .

**Comment by pratyushmp** [comment]
@pawan2806 Use Firebase Realtime DB

**Comment by pratyushmp** [comment]
@pawan2806 Status?
