### ISSUE TITLE
Adding functionality  to the profile button  on homepage.

### ISSUE THREAD

**Issue by Borahb** [pratyushmp/Batua#49]
I want to add a profile screen for the users.
#gssoc21

**Comment by pratyushmp** [comment]
Sure! @Borahb . Could you design a mock UI so that we can have an idea of what you are planning to keep in the profile section

**Comment by Borahb** [comment]
okay

**Comment by Borahb** [comment]
This is just a tentative UI, the actual UI will vary. You can mention if any feature can be added.

![scr](https://user-images.githubusercontent.com/49881148/112327350-5d8a4000-8cdb-11eb-9da8-15ac5530a7d9.png)

**Comment by pratyushmp** [comment]
Yeah @Borahb . Looks Good make sure you follow the design and colors used in ```constants.dart``` file.

**Comment by pratyushmp** [comment]
@Borahb Status of the profile page?

**Comment by Borahb** [comment]
It's ready. By tomorrow I will send the PR
