### ISSUE TITLE
Project Setup Instructions for getting started with their Contribution

### ISSUE THREAD

**Issue by Sahil-kachhap** [pratyushmp/Batua#5]
I went through the Readme.md file where you have attached your YouTube video having instructions for the local project setup. 

- Can I complete that project Setup Section with Git bash commands . Newcomers will have either of the option to follow among the readme instructions and that video.

- the project setup instructions will include 
   
    1. Cloning the Repo 
    2. Creating Remotes to the forked and to this repo 
          for fetching or pulling recent changes .
    3. Pushing Changes and Creating Branches.
    
- Any further details would be discussed over here if needed 

- So if this issue seems legitimate than I would like to be assigned to complete this work .

**Comment by pratyushmp** [comment]
Sure @Sahil-kachhap. Make a CONTRIBUTING.md file and add the instructions there.
