### ISSUE TITLE
No structuring of files inside lib folder

### ISSUE THREAD

**Issue by Borahb** [pratyushmp/Batua#53]
There is no folder structure inside lib folder, files are placed in a haphazard way. I want to go for proper structuring of files inside it.
#gssoc21

![Screenshot (463)](https://user-images.githubusercontent.com/49881148/112332609-e2775880-8cdf-11eb-9058-241e0cadf3e9.png)

**Comment by pratyushmp** [comment]
Go ahead @Borahb
