### ISSUE TITLE
Add Show/hide password button

### ISSUE THREAD

**Issue by rakshitkamboj** [pratyushmp/Batua#55]
I want to add a eye icon to the login screen near password form that will allow user to show/hide their password .
As If user by mistake inputs wrong password it becomes very difficult to correct it.
This feature will solve that problem.

I am also a GSSoC'21 participant.

**Comment by pratyushmp** [comment]
Good idea @rakshitkamboj . You can start working on it!

**Comment by rakshitkamboj** [comment]
Thanks @pratyushmp for assigning it to me.
I will do my best.
