### ISSUE TITLE
On Generate Named Routes

### ISSUE THREAD

**Issue by SapinderSingh** [pratyushmp/Batua#56]
### Feature request :
The app should use On Generate Named routes.

### Is your feature request related to a problem? Please describe : (optional)
Yes. Currently the app is using 'on the fly' routes, which are very difficult to maintain. 
 
### Describe the solution you'd like :
On Generate routes are very easy to maintain as all the routing logic sits in one file only.

### Describe how this feature will be useful to our readers :
On Generate routes are very easy to maintain and use. 

<hr/>

**Note:**
* I am a participant of GSSOC 21. Please assign this issue to me.

**Comment by pratyushmp** [comment]
@SapinderSingh Go ahead!

**Comment by SapinderSingh** [comment]
@pratyushmp Please add GSSOC label to this issue. Thanks.
