### ISSUE TITLE
No modal bottom screen coming, when user taps on the floating action button.

### ISSUE THREAD

**Issue by SapinderSingh** [pratyushmp/Batua#64]
### **Describe the bug:**
No bottom modal screen comes, when user taps on the floating action button. The showBottomModalSheet method is linked to the button in code, but there is no modal bottom sheet attached to it. 

### **To Reproduce:**
1. Go to Home Screen
2. Click on the Floating Action Button.
3. See, there is no bottom sheet. 

### **Expected behavior:**
A bottom sheet should come up.

I am a participant of GSSOC 21. I can work on this issue. Please assign me this issue under GSSOC 21.

**Note:**
Please provide me the design of the bottom sheet.

**Comment by pratyushmp** [comment]
@SapinderSingh I am assigning you issue #26 (Create Goal Page), its the screen which needs to be rendered after clicking the floating action button.

**Comment by pratyushmp** [comment]
@SapinderSingh Refer to issue #26 .
