### ISSUE TITLE
Navigate First Time users to user_details_screen.dart and store the details in firebase

### ISSUE THREAD

**Issue by pratyushmp** [pratyushmp/Batua#68]

**Comment by pawan2806** [comment]
Hi can you assign it to me under gssoc21?

**Comment by pratyushmp** [comment]
Go ahead @pawan2806 !

**Comment by pratyushmp** [comment]
@pawan2806 the user_details_screen.dart file is already made you just need to navigate and store all the details entered in it in firebase. Also the email field in user_details_screen.dart should be automatically filled based on the email id given during login.

**Comment by pratyushmp** [comment]
@pawan2806 Status?

**Comment by pawan2806** [comment]
> @pawan2806 Status?

sorry for the delay, got caught in exams. Will make PR soon

**Comment by pawan2806** [comment]
@pratyushmp what should I use to check if user is first time user or not? Shared pref ?

**Comment by pratyushmp** [comment]
@pawan2806 Use HiveDB, it would be faster.

**Comment by pratyushmp** [comment]
@pawan2806 progress?

**Comment by Borahb** [comment]
@pratyushmp   Can I work on this issue?

**Comment by pratyushmp** [comment]
@Borahb Issue is assigned to you

**Comment by Borahb** [comment]
@pratyushmp  have a look at this. The data is saved on cloud firestore. Is it Okay?

https://user-images.githubusercontent.com/49881148/115983104-e509ee00-a5bc-11eb-9614-ff462d1ce344.mp4

**Comment by pratyushmp** [comment]
Looks good @Borahb . Just Make sure that the email entered in Sign Up page is auto filled in user details screen, so that the user does not enter the email again.

**Comment by Borahb** [comment]
@pratyushmp  for the email in user details page, I have added autofill using hints. It will suggest the email, user just have to select the email. Will it work.

**Comment by pratyushmp** [comment]
It is kinda redundant actually, I would suggest just fill it from the previous screen. If you need any help in implementing that, just let me know.

**Comment by Borahb** [comment]
@pratyushmp  I am facing issue regarding filling the email. So like should the email remain still in that section , not able to edit  or the user should be able to edit it.

**Comment by Borahb** [comment]
![Screenshot_1619414834](https://user-images.githubusercontent.com/49881148/116033018-4219a880-a67e-11eb-97e6-67794f6abe17.png)

**Comment by pratyushmp** [comment]
Yup perfect

**Comment by pratyushmp** [comment]
make a PR
