### ISSUE TITLE
Adding some sections and Modifying the Readme.md file

### ISSUE THREAD

**Issue by DOOMSTERR** [pratyushmp/Batua#71]
## Request ✨
Hello sir, I want to modify the readme.md file.

### Modifying it by adding 

1.)Adding shield batches in different colors for(at center-top):
-> issues-open
-> pull_request-open
-> total no. of forks
-> total no. of stars

2.) Sections
->Feature Section.
->Sneak and Peek (changing the name of UI Design, and styling it).
->Tech Stack Section.
->Contributing guidelines (styling and alining it in the proper way to look good)
->In Contributor Section adding,
>Project Manager/Admin Section

-> I'll also be adding emojis to make it look more attractive and beautiful.

I really want to make it look more attractive and beautiful. 
@pratyushmp @nirala96 sir, please allow me to do so, by assigning me the issue under the GSSOC21 label & level label.

Thank you.

**Comment by pratyushmp** [comment]
Go ahead @DOOMSTERR .
