### ISSUE TITLE
Fetching user details to profile page.

### ISSUE THREAD

**Issue by Borahb** [pratyushmp/Batua#72]
I want to make the profile page working as it is just  UI now so that details of the user are shown on the profile page with the ability to edit the details.

#gssoc21 participant

**Comment by pratyushmp** [comment]
@Borahb you can start working on this issue only after issue #68 is completed!

**Comment by Borahb** [comment]
@pratyushmp  When will issue #68  get completed, so that I can start working on this issue?

**Comment by Borahb** [comment]
@pratyushmp   Can I start working  on this issue ?

**Comment by pratyushmp** [comment]
Yess you can start now.
