### ISSUE TITLE
App Settings Screen

### ISSUE THREAD

**Issue by SapinderSingh** [pratyushmp/Batua#75]
### Feature request :
There should be an app settings screen. 

### Is your feature request related to a problem? Please describe : (optional)
On the profile page, there is app settings tile, which doesn't do anything. 

### Describe the solution you'd like :
I would like to add a settings screen, so user can go to that screen, by clicking on the tile. 

### Additional context :
Please provide me a screenshot for the settings screen.

<hr/>

**Note:**
* I am a participant of GSSOC 21.

**Comment by pratyushmp** [comment]
@SapinderSingh You can start working on this!

**Comment by SapinderSingh** [comment]
> @SapinderSingh You can start working on this!

Please provide me a screenshot for the settings screen.
