### ISSUE TITLE
Bottom Navigation Bar behavior. 

### ISSUE THREAD

**Issue by SapinderSingh** [pratyushmp/Batua#82]
### **Describe the bug:**
The bottom navigation bar should darken the selected icon and lighten the unselected. But, the icons' colors are fixed, it should change, when selects the other icon as in the mockups of the app.

 

### **Expected behavior:**
The icons' colors should change, when selected. 

### **Screenshots:**
![1](https://user-images.githubusercontent.com/29424616/116800705-4253f100-ab21-11eb-9dd1-2ee48da97756.jpeg)

**Note:**
* I am a participant of GSSoC'21.

**Comment by pratyushmp** [comment]
@SapinderSingh you can go ahead!

**Comment by Alifbhanvadiya14** [comment]
is this issue assigned?

**Comment by SapinderSingh** [comment]
> is this issue assigned?

@Alifbhanvadiya14 Yes
